steps:
- name: 'maven'
  entrypoint: 'mvn'
  args: ['clean', 'install']

#build image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/prime-plating-376611/cicd-empapp-cloud-run', '.']
  
 #push image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/prime-plating-376611/cicd-empapp-cloud-run']
  

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['run', 'deploy', 'empapp-service', '--image', 'gcr.io/prime-plating-376611/cicd-empapp-cloud-run', '--set-env-vars', 'PROJECT_ID=prime-plating-376611',  '--region', 'us-central1', '--allow-unauthenticated']


images:
 - gcr.io/prime-plating-376611/cicd-empapp-cloud-run
 